spring.application.name=service
spring.config.import=configserver:

logging.level.org.springframework.modulith=DEBUG
logging.level.org.springframework.integration=DEBUG
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG